version: '3.8'

services:
  app:
    image: mini-facebook-back
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 in the container to port 3000 on the host
    depends_on:
      - db
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - MASTER_KEY=${MASTER_KEY}
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    networks:
      - app-network

  db:
    image: postgres:14  # Use the official PostgreSQL image
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"  # Map port 5432 in the container to port 5432 on the host
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist PostgreSQL data
    networks:
      - app-network

volumes:
  postgres-data:  # Named volume for persistent PostgreSQL data

networks:
  app-network:  # Custom network for inter-service communication